# frozen_string_literal: true

class Ad < Sequel::Model
  def validate
    super
    validates_presence %i[title description city]
  end
end

# Table: ads
# Columns:
#  id          | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  title       | character varying(255)      | NOT NULL
#  description | text                        | NOT NULL
#  city        | character varying(255)      | NOT NULL
#  lat         | double precision            |
#  lon         | double precision            |
#  created_at  | timestamp without time zone |
#  updated_at  | timestamp without time zone |
#  user_id     | bigint                      | NOT NULL
# Indexes:
#  ads_pkey          | PRIMARY KEY btree (id)
#  ads_user_id_index | btree (user_id)
