# frozen_string_literal: true

class UserSession < Sequel::Model
  plugin :uuid

  many_to_one :user

  def validate
    super

    validates_presence :uuid, message: I18n.t('model.errors.user_session.uuid.blank')
  end
end

# Table: user_sessions
# Columns:
#  id         | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  uuid       | uuid                        | NOT NULL
#  created_at | timestamp without time zone | NOT NULL
#  updated_at | timestamp without time zone | NOT NULL
#  user_id    | bigint                      | NOT NULL
# Indexes:
#  user_sessions_pkey          | PRIMARY KEY btree (id)
#  user_sessions_user_id_index | btree (user_id)
#  user_sessions_uuid_index    | btree (uuid)
# Foreign key constraints:
#  user_sessions_user_id_fkey | (user_id) REFERENCES users(id)
