# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'anyway_config'
gem 'dry-initializer'
gem 'dry-validation'
gem 'i18n'
gem 'jsonapi-serializer'
gem 'puma'
gem 'rake'
gem 'roda'
gem 'roda-symbolized_params'

group :development, :test do
  gem 'factory_bot'
  gem 'pry'
end

group :development do
  gem 'roda-enhanced_logger'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
end
