# frozen_string_literal: true

class Ad < Sequel::Model
  def validate
    super

    validates_presence :city, message: I18n.t(:blank, scope: 'model.errors.ad.city')
    validates_presence :title, message: I18n.t(:blank, scope: 'model.errors.ad.title')
    validates_presence :description, message: I18n.t(:blank, scope: 'model.errors.ad.description')
  end
end

# Table: ads
# Columns:
#  id          | bigint                      | PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
#  title       | character varying           | NOT NULL
#  description | text                        | NOT NULL
#  city        | character varying           | NOT NULL
#  lat         | double precision            |
#  lon         | double precision            |
#  created_at  | timestamp without time zone | NOT NULL
#  updated_at  | timestamp without time zone | NOT NULL
#  user_id     | bigint                      | NOT NULL
# Indexes:
#  ads_pkey          | PRIMARY KEY btree (id)
#  ads_user_id_index | btree (user_id)
