# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'dry-initializer'
gem 'jsonapi-serializer'
gem 'puma'
gem 'rake'
gem 'roda'
gem 'roda-i18n'
gem 'roda-symbolized_params'
gem 'sequel'
gem 'sequel_pg', require: 'sequel'
gem 'zeitwerk'

group :development, :test do
  gem 'factory_bot'
  gem 'pry'
end

group :development do
  gem 'roda-enhanced_logger'
  gem 'sequel-annotate'
end

group :test do
  gem 'rack-test'
  gem 'rspec'
end
